apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  volumes:
    - name: sql-volume
      persistentVolumeClaim:
        claimName: mysql-pv-claim
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    volumeMounts:
      - name: sql-volume
        mountPath: /data
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: app-secret
          key: DB_Password
 
